# Colores One Dark (hypr/colors/one-dark.css)
# background              #121212
foreground              #F0F0F0
cursor                  #F0F0F0

selection_background    #121212
selection_foreground    #F0F0F0

background_opacity              0.4

# --- Normal ---
# color0  #121212
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #73daca
color7  #F0F0F0

# --- Bright ---
color8   #121212
color9   #f7768e
color10  #9ece6a
color11  #e0af68
color12  #7aa2f7
color13  #bb9af7
color14  #73daca
color15  #F0F0F0

# foreground              #F0F0F0
# background              #121212
