splash = false
ipc = true

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/walt/comics/sm-2099.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Pictures/walt/comics/sm-2099.jpg
    fit_mode = cover
}