###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = ~/.config/rofi/app-launcher/app-launcher.sh
$wallPicker = ~/.config/rofi/wallpaper-launcher/wallpaper-launcher.sh
$notificationCenter = swaync-client -t
$powerPicker = ~/.config/rofi/power-launcher/power-launcher.sh
$browser = firefox

#################
### AUTOSTART ###
#################
exec-once = waybar
exec-once = swaync
exec-once = awww-daemon
# exec-once = hyprpaper
# exec-once = ~/.config/scripts/restore_wall.sh
# exec-once = eww -c ~/.config/eww/left_bar daemon
# exec-once = sleep 1 && eww -c ~/.config/eww/left_bar open-many main pfp song sys_usg song_prog song_ctl audio quote sys_tray time
exec-once = wifi-manager
exec-once = ~/.config/scripts/battery_notify.sh
# exec-once = bongocat --layer background &
exec-once = ~/.config/hypr/scripts/kb-on-ac.sh
exec-once = swayosd-server

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_SIZE,26
# env = HYPRCURSOR_SIZE,26
env = XCURSOR_THEME, Qogir-Dark

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# SOURCE FILES
source = ./configs/monitors.conf
source = ./configs/animations.conf
source = ./configs/userprefs.conf
source = ./configs/keybindings.conf
source = ./configs/windowrules.conf
source = ./configs/layer_rules.conf
# source = ~/.config/hypr/hyprpaper.conf
