layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace zed

layerrule = blur on, ignore_alpha 0, xray 0, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0, xray 0, match:namespace swaync-notification-window

layerrule = blur on, match:namespace wifi-manager
layerrule = blur on, match:namespace code
layerrule = blur on, match:namespace rofi
# layerrule = blur on, match:namespace firefox
layerrule = blur on, match:namespace obsidian
layerrule = blur on, match:namespace xdg-desktop-portal-gtk
